-- MySQL Script generated by MySQL Workbench
-- 09/24/15 14:37:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cat_dcms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cat_dcms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cat_dcms` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `cat_dcms` ;

-- -----------------------------------------------------
-- Table `cat_dcms`.`cus_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cat_dcms`.`cus_person` (
  `PersonID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Fname` VARCHAR(45) NULL COMMENT '',
  `Lname` VARCHAR(45) NULL COMMENT '',
  `Phone` VARCHAR(45) NULL COMMENT '',
  `Email` VARCHAR(45) NULL COMMENT '',
  `Password` VARCHAR(45) NULL COMMENT '',
  `TypePerson` VARCHAR(45) NULL COMMENT '',
  `IDCard` INT NULL COMMENT '',
  `Position` VARCHAR(45) NULL COMMENT '',
  `CustomerID` INT NULL COMMENT '',
  PRIMARY KEY (`PersonID`)  COMMENT '',
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cat_dcms`.`cus_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cat_dcms`.`cus_customer` (
  `CustomerID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `PrefixID` VARCHAR(45) NULL COMMENT '',
  `CustomerStatus` VARCHAR(45) NULL COMMENT '',
  `CustomerName` VARCHAR(45) NULL COMMENT '',
  `Email` VARCHAR(45) NULL COMMENT '',
  `Phone` VARCHAR(45) NULL COMMENT '',
  `Fax` VARCHAR(45) NULL COMMENT '',
  `Address` VARCHAR(45) NULL COMMENT '',
  `Township` VARCHAR(45) NULL COMMENT '',
  `City` VARCHAR(45) NULL COMMENT '',
  `Province` VARCHAR(45) NULL COMMENT '',
  `Zipcode` INT NULL COMMENT '',
  `Country` VARCHAR(45) NULL COMMENT '',
  `BusinessTypeID` INT NULL COMMENT '',
  PRIMARY KEY (`CustomerID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cat_dcms`.`cus_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cat_dcms`.`cus_service` (
  `ServiceID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `NameService` VARCHAR(45) NULL COMMENT '',
  `Detail` TEXT NULL COMMENT '',
  `ServiceType` VARCHAR(45) NULL COMMENT '',
  `ServiceStatus` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`ServiceID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cat_dcms`.`cus_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cat_dcms`.`cus_order` (
  `OrderID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `OrderPreID` VARCHAR(45) NULL COMMENT '',
  `OrderIDOld` VARCHAR(45) NULL COMMENT '',
  `CustomerID` INT NULL COMMENT '',
  `DomainName` VARCHAR(45) NULL COMMENT '',
  `Location` VARCHAR(45) NULL COMMENT '',
  `StatusOrder` VARCHAR(45) NULL COMMENT '',
  `DateTimeCreate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `DateTimeUpdate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  `CreateBy` INT NULL COMMENT '',
  `UpdateBy` INT NULL COMMENT '',
  PRIMARY KEY (`OrderID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cat_dcms`.`cus_orderBundleNetwork`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cat_dcms`.`cus_orderBundleNetwork` (
  `orderBundleNetworkID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `OrderID` INT NULL COMMENT '',
  `BundleNetwork` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`orderBundleNetworkID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cat_dcms`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cat_dcms`.`ticket` (
  `TicketID` INT NOT NULL COMMENT '',
  `PersonID` INT NULL COMMENT '',
  `Topic` VARCHAR(45) NULL COMMENT '',
  `Detail` TEXT NULL COMMENT '',
  `TicketStatus` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`TicketID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cat_dcms`.`ticketEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cat_dcms`.`ticketEvent` (
  `TicketEventID` INT NOT NULL COMMENT '',
  `TicketID` INT NULL COMMENT '',
  `PersonID` INT NULL COMMENT '',
  `TicketEvent` TEXT NULL COMMENT '',
  PRIMARY KEY (`TicketEventID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cat_dcms`.`entryIDC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cat_dcms`.`entryIDC` (
  `EntryIDCID` INT NOT NULL COMMENT '',
  `TimeIn` DATETIME NULL COMMENT '',
  `TimeOut` DATETIME NULL COMMENT '',
  `Note` TEXT NULL COMMENT '',
  `DateTimeCreate` INT NULL COMMENT '',
  PRIMARY KEY (`EntryIDCID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cat_dcms`.`entryIDCPerson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cat_dcms`.`entryIDCPerson` (
  `EntryIDCPersonID` INT NOT NULL COMMENT '',
  `EntryIDCID` INT NULL COMMENT '',
  `PersonID` INT NULL COMMENT '',
  `Name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`EntryIDCPersonID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cat_dcms`.`entryIDCArea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cat_dcms`.`entryIDCArea` (
  `EntryIDCAreaID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `EntryIDCID` INT NULL COMMENT '',
  `Area` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`EntryIDCAreaID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cat_dcms`.`resourceSwitchPort`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cat_dcms`.`resourceSwitchPort` (
  `ResourceSwitchPortID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ResourceSwitchID` INT NULL COMMENT '',
  `PortNumber` INT NULL COMMENT '',
  `PortType` VARCHAR(45) NULL COMMENT '',
  `Uplink` TINYINT NULL COMMENT '',
  `PersonID` INT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ResourceSwitchPortID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cat_dcms`.`resourceSwitch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cat_dcms`.`resourceSwitch` (
  `ResourceSwitchID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `SwitchName` VARCHAR(45) NULL COMMENT '',
  `SwitchIP` VARCHAR(45) NULL COMMENT '',
  `TotalPort` VARCHAR(45) NULL COMMENT '',
  `SnmpCommuPublic` VARCHAR(45) NULL COMMENT '',
  `SnmpCommuPrivate` VARCHAR(45) NULL COMMENT '',
  `SwitchType` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`ResourceSwitchID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cat_dcms`.`resourceIP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cat_dcms`.`resourceIP` (
  `ResourceIpID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `IP` VARCHAR(45) NULL COMMENT '',
  `NetworkIP` VARCHAR(45) NULL COMMENT '',
  `Subnet` VARCHAR(45) NULL COMMENT '',
  `VlanID` INT NULL COMMENT '',
  `PersonID` INT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ResourceIpID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cat_dcms`.`resourceRack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cat_dcms`.`resourceRack` (
  `ResourceRackID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Position` VARCHAR(45) NULL COMMENT '',
  `SubPosition` VARCHAR(45) NULL COMMENT '',
  `RackType` VARCHAR(45) NULL COMMENT '',
  `RackSize` INT NULL COMMENT '',
  `PersonID` INT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ResourceRackID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cat_dcms`.`resourceService`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cat_dcms`.`resourceService` (
  `ResourceServiceID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  `Detail` VARCHAR(45) NULL COMMENT '',
  `Tag` TEXT NULL COMMENT '',
  `PersonID` INT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ResourceServiceID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cat_dcms`.`cus_orderDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cat_dcms`.`cus_orderDetail` (
  `OrderDetailID` INT NOT NULL COMMENT '',
  `OrderID` INT NULL COMMENT '',
  `ServiceID` INT NULL COMMENT '',
  `OrderDetailStatus` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`OrderDetailID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cat_dcms`.`cus_customer_bussinessType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cat_dcms`.`cus_customer_bussinessType` (
  `BussinessTypeID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `BussinessType` VARCHAR(45) NULL COMMENT '',
  `StatusBussinessType` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`BussinessTypeID`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
